stages:
  - build
  - test

build_job:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:7.0
  script:
    - dotnet restore
    - dotnet build


test_job:
    stage: test
    image: mcr.microsoft.com/dotnet/sdk:7.0
    script:
    - dotnet test -- configuration Release
